apiVersion: v2
name: mern-app
description: A Helm chart for MERN Stack Application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - mern
  - mongodb
  - express
  - react
  - nodejs
maintainers:
  - name: Your Name
    email: your.email@example.com
